Fix bug - Remove "Delete all products" button as it calls an unimplemented method (#3782)
Summary:
## Description

we removed the feature to delete all products on facebook catalog here - https://github.com/facebook/facebook-for-woocommerce/pull/3623

but the UI still remains -
 {F1984243698}
And when people click on it , it raises this error and the page crashes.
```
Undefined property: WooCommerce\Facebook\Jobs\JobManager::$delete_all_products in** ~/local-site1/app/public/wp-content/plugins/facebook-for-woocommerce/includes/Utilities/DebugTools.php **on line** 117 **

Fatal error: Uncaught Error: Call to a member function queue_start()
```
 {F1984243699}
Hence in this change, we remove the button altogether and any relevant tests.

### Type of change

- Fix (non-breaking change which fixes an issue)

## Checklist

- [✔️] I have commented my code, particularly in hard-to-understand areas, if any.
- [✔️] I have confirmed that my changes do not introduce any new PHPCS warnings or errors.
- [✔️] I have checked plugin debug logs that my changes do not introduce any new PHP warnings or FATAL errors.
- [✔️] I followed general Pull Request best practices. Meta employees to follow this [wiki]([url](https://fburl.com/wiki/2cgfduwc)).
- [✔️] I have added tests (if necessary) and all the new and existing unit tests pass locally with my changes.
- [✔️] I have completed dogfooding and QA testing, or I have conducted thorough due diligence to ensure that it does not break existing functionality.
- [] I have updated or requested update to plugin documentations (if necessary). Meta employees to follow this [wiki]([url](https://fburl.com/wiki/nhx73tgs)).

## Changelog entry

Fix bug - Remove "Delete all products" button as it calls an unimplemented method

Pull Request resolved: https://github.com/facebook/facebook-for-woocommerce/pull/3782

Test Plan:
Tested locally and attached screenshots
## Screenshots
### Before
 {F1984243702}
### After

 {F1984243704}

Reviewed By: devbodaghe

Differential Revision: D89373278

Pulled By: immadhavv

fbshipit-source-id: dc324f6a7bcb37ffedd791a4f51a54ff3bd202af